apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networkmetrics.network.example.com
spec:
  group: network.example.com
  names:
    plural: networkmetrics
    singular: networkmetric
    kind: NetworkMetrics
    shortNames:
      - nm
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                metrics:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true